### ISSUE TITLE
Cartoon of A2C

### ISSUE THREAD

**Issue by Michi-123** [rgilman33/baselines-A2C#1]
Thank you for A2C story by cartoon.
I want to use this story by the other illustration in educational commercial site. Is it all right to use your cranberry story by different cartoon?
Thank you.

**Comment by Michi-123** [comment]
Like this
[Spot's story](https://docs.google.com/presentation/d/e/2PACX-1vQ_5Gb19XVbiauexugRYqNlm8MRmwahQ9Z4otM4egvYgE4ZCfemlqzUv968xcxisaKp-afLH3aEGWKN/pub?start=false&loop=false&delayms=3000&slide=id.gd28c1e9257_1_19)

**Comment by rgilman33** [comment]
Sure no problem

**Comment by Michi-123** [comment]
Thank you very much.
